SELECT scientific_name 
FROM fire_characteristics
INNER JOIN shudong_flame_and_litter
ON LOWER(TRIM(BOTH ' ' FROM fire_characteristics.scientific_name)) = LOWER(TRIM(BOTH ' ' FROM shudong_flame_and_litter.species))
GROUP BY scientific_name





SELECT nutrients."Species_#", species_latin_name 
FROM nutrients 
LEFT JOIN species
ON nutrients."Species_#" = species."Species_#"
WHERE species_latin_name LIKE ANY (ARRAY[
'Abies balsamea%',
'Abies concolor%',
'Abies fraseri%',
'Acer barbatum%',
'Acer leucoderme%',
'Acer negundo%',
'Acer nigrum%',
'Acer pensylvanicum%',
'Acer platanoides%',
'Acer rubrum%',
'Acer saccharinum%',
'Acer saccharum%',
'Acer spicatum%',
'Aesculus flava%',
'Aesculus glabra%',
'Ailanthus altissima%',
'Albizia julibrissin%',
'Alnus glutinosa%',
'Amelanchier arborea%',
'Annona glabra%',
'Asimina triloba%',
'Avicennia germinans%',
'Betula alleghaniensis%',
'Betula lenta%',
'Betula nigra%',
'Betula papyrifera%',
'Betula populifolia%',
'Bursera simaruba%',
'Carpinus caroliniana%',
'Carya aquatica%',
'Carya carolinae-septentrionalis%',
'Carya cordiformis%',
'Carya floridana%',
'Carya glabra%',
'Carya illinoinensis%',
'Carya laciniosa%',
'Carya myristiciformis%',
'Carya ovalis%',
'Carya ovata%',
'Carya pallida%',
'Carya texana%',
'Carya tomentosa%',
'Castanea dentata%',
'Castanea mollissima%',
'Castanea pumila%',
'Casuarina lepidophloia%',
'Catalpa bignonioides%',
'Catalpa speciosa%',
'Celtis laevigata%',
'Celtis occidentalis%',
'Cercis canadensis%',
'Chamaecyparis thyoides%',
'Cinnamomum camphora%',
'Cladrastis kentukea%',
'Coccoloba diversifolia%',
'Coccothrinax argentata%',
'Conocarpus erectus%',
'Cornus florida%',
'Cotinus obovatus%',
'Crataegus crus-galli%',
'Crataegus mollis%',
'Diospyros virginiana%',
'Elaeagnus angustifolia%',
'Eucalyptus grandis%',
'Eugenia rhombea%',
'Fagus grandifolia%',
'Ficus aurea%',
'Fraxinus americana%',
'Fraxinus caroliniana%',
'Fraxinus nigra%',
'Fraxinus pennsylvanica%',
'Fraxinus profunda%',
'Fraxinus quadrangulata%',
'Ginkgo biloba%',
'Gleditsia aquatica%',
'Gleditsia triacanthos%',
'Gordonia lasianthus%',
'Guapira discolor%',
'Gymnocladus dioicus%',
'Halesia carolina%',
'Halesia diptera%',
'Ilex opaca%',
'Juglans cinerea%',
'Juglans nigra%',
'Juniperus virginiana%',
'Laguncularia racemosa%',
'Larix laricina%',
'Liquidambar styraciflua%',
'Liriodendron tulipifera%',
'Maclura pomifera%',
'Magnolia acuminata%',
'Magnolia fraseri%',
'Magnolia grandiflora%',
'Magnolia macrophylla%',
'Magnolia tripetala%',
'Magnolia virginiana%',
'Malus angustifolia%',
'Malus coronaria%',
'Malus ioensis%',
'Melaleuca quinquenervia%',
'Melia azedarach%',
'Metopium toxiferum%',
'Morus alba%',
'Morus rubra%',
'Nyssa aquatica%',
'Nyssa biflora%',
'Nyssa ogeche%',
'Nyssa sylvatica%',
'Ostrya virginiana%',
'Oxydendrum arboreum%',
'Paulownia tomentosa%',
'Persea borbonia%',
'Picea abies%',
'Picea glauca%',
'Picea mariana%',
'Picea pungens%',
'Picea rubens%',
'Pinus banksiana%',
'Pinus clausa%',
'Pinus echinata%',
'Pinus elliottii%',
'Pinus glabra%',
'Pinus nigra%',
'Pinus palustris%',
'Pinus pungens%',
'Pinus resinosa%',
'Pinus rigida%',
'Pinus serotina%',
'Pinus spp.%',
'Pinus strobus%',
'Pinus sylvestris%',
'Pinus taeda%',
'Pinus virginiana%',
'Piscidia piscipula%',
'Planera aquatica%',
'Platanus occidentalis%',
'Populus alba%',
'Populus balsamifera%',
'Populus deltoides%',
'Populus grandidentata%',
'Populus heterophylla%',
'Populus tremuloides%',
'Prunus americana%',
'Prunus avium%',
'Prunus cerasus%',
'Prunus nigra%',
'Prunus pensylvanica%',
'Prunus persica%',
'Prunus serotina%',
'Prunus virginiana%',
'Pseudotsuga menziesii%',
'Quercus alba%',
'Quercus bicolor%',
'Quercus coccinea%',
'Quercus ellipsoidalis%',
'Quercus falcata%',
'Quercus ilicifolia%',
'Quercus imbricaria%',
'Quercus incana%',
'Quercus laevis%',
'Quercus laurifolia%',
'Quercus lyrata%',
'Quercus macrocarpa%',
'Quercus margarettae%',
'Quercus marilandica%',
'Quercus michauxii%',
'Quercus minima%',
'Quercus montana%',
'Quercus muehlenbergii%',
'Quercus nigra%',
'Quercus oglethorpensis%',
'Quercus pagoda%',
'Quercus palustris%',
'Quercus phellos%',
'Quercus prinoides%',
'Quercus rubra%',
'Quercus shumardii%',
'Quercus similis%',
'Quercus sinuata%',
'Quercus stellata%',
'Quercus texana%',
'Quercus velutina%',
'Quercus virginiana%',
'Rhizophora mangle%',
'Robinia pseudoacacia%',
'Sabal palmetto%',
'Salix alba%',
'Salix amygdaloides%',
'Salix bebbiana%',
'Salix caroliniana%',
'Salix nigra%',
'Salix pyrifolia%',
'Salix x sepulcralis%',
'Sassafras albidum%',
'Sideroxylon lanuginosum%',
'Sideroxylon salicifolium%',
'Sorbus americana%',
'Sorbus aucuparia%',
'Sorbus decora%',
'Swietenia mahagoni%',
'Taxodium ascendens%',
'Taxodium distichum%',
'Thrinax morrisii%',
'Thuja occidentalis%',
'Tilia americana%',
'Triadica sebifera%',
'Tsuga canadensis%',
'Tsuga caroliniana%',
'Ulmus alata%',
'Ulmus americana%',
'Ulmus crassifolia%',
'Ulmus pumila%',
'Ulmus rubra%',
'Ulmus serotina%',
'Ulmus thomasii%',
'Vernicia fordii%'
])
GROUP BY nutrients."Species_#", species_latin_name



-- What methods were used?
SELECT analytical_method."Method_description" FROM analytical_method GROUP BY "Method_description" ORDER BY "Method_description"

-- What units are given?
SELECT "C_unit", "N_unit", count("C_unit") 
FROM nutrients 
WHERE "C_unit" != '9999' 
GROUP BY "C_unit", "N_unit" 
ORDER BY count DESC

-- How many rows have measurements for C and N?  (Only two rows have "Foliage_C_%"!)
SELECT "Foliage_C_%", "Foliage_N_%", COUNT("Foliage_C_%") 
FROM nutrients 
WHERE "Foliage_C_%" != '9999'
GROUP BY "Foliage_C_%", "Foliage_N_%" 
ORDER BY count DESC

SELECT "Foliage_C", COUNT("Foliage_C") FROM nutrients GROUP BY "Foliage_C"

-- Do the %_Comments clear up what units were used? (no.)
SELECT "%_comments", COUNT("%_comments") FROM nutrients GROUP BY "%_comments" ORDER BY "%_comments"
