
CREATE TABLE copy_fire_characteristics (
  fia_species_code	bigint,
  common_name	text,
  scientific_name	text,
  genus	text,
  species	text,
  flame_height_cm	text,
  flame_duration_s	text,
  smoulder_duration_s	text,
  percent_consumed	text,
  fireline_intensity_kwm	text,
  outer_bark_thickness_cm	text,
  inner_bark_thickness_cm	text,
  fire_trait_citation	text,
  family	text,
  mycorrhizal_type	text,
  tpa	text,
  baa	text,
  tpa_perc	text,
  baa_perc	text,
  tpa_se	text,
  baa_se	text,
  tpa_perc_se	text,
  baa_perc_se	text,
  nplots_tree	text,
  nplots_area	text,
  comments	text,
  mean_perc_litter_c	text,
  mean_perc_litter_c_source text,
  mean_perc_litter_n	text,
  mean_perc_litter_n_source text,
  mean_perc_litter_p	text,
  mean_perc_litter_p_source text,
  mean_litter_cn	text,
  mean_litter_cn_source text,
  mean_litter_np	text,
  mean_litter_np_source text,
  mean_perc_litter_lignin	text,
  mean_litter_ligninn	text,
  lignin_source text,
  mean_litter_k	text,
  mean_litter_k_source text,
  litter_citation	text,
  try_mean_bark_thickness_cm	text,
  mean_bark_thickness_cm	text,
  bark_thickness_citation	text,
  bark_diameter_ratio	double precision,
  bark_diameter_source	text
)

-- NEW ROWS:
-- 	mean_litter_k_source
-- 	lignin_source
-- 	mean_litter_np_source
-- 	mean_litter_cn_source
-- 	mean_perc_litter_p_source
-- 	mean_perc_litter_n_source
-- 	mean_perc_litter_c_source


INSERT INTO copy_fire_characteristics (
  fia_species_code,
  common_name,
  scientific_name,
  genus,
  species,
  flame_height_cm,
  flame_duration_s,
  smoulder_duration_s,
  percent_consumed,
  fireline_intensity_kwm,
  outer_bark_thickness_cm,
  inner_bark_thickness_cm,
  fire_trait_citation,
  family,
  mycorrhizal_type,
  tpa,
  baa,
  tpa_perc,
  baa_perc,
  tpa_se,
  baa_se,
  tpa_perc_se,
  baa_perc_se,
  nplots_tree,
  nplots_area,
  comments,
  mean_perc_litter_c,
  mean_perc_litter_n,
  mean_perc_litter_p,
  mean_litter_cn,
  mean_litter_np,
  mean_perc_litter_lignin,
  mean_litter_ligninn,
  mean_litter_k,
  litter_citation,
  try_mean_bark_thickness_cm,
  mean_bark_thickness_cm,
  bark_thickness_citation,
  bark_diameter_ratio,
  bark_diameter_source
)
SELECT 
  fia_species_code,
  common_name,
  scientific_name,
  genus,
  species,
  flame_height_cm,
  flame_duration_s,
  smoulder_duration_s,
  percent_consumed,
  fireline_intensity_kwm,
  outer_bark_thickness_cm,
  inner_bark_thickness_cm,
  fire_trait_citation,
  family,
  mycorrhizal_type,
  tpa,
  baa,
  tpa_perc,
  baa_perc,
  tpa_se,
  baa_se,
  tpa_perc_se,
  baa_perc_se,
  nplots_tree,
  nplots_area,
  comments,
  mean_perc_litter_c,
  mean_perc_litter_n,
  mean_perc_litter_p,
  mean_litter_cn,
  mean_litter_np,
  mean_perc_litter_lignin,
  mean_litter_ligninn,
  mean_litter_k,
  litter_citation,
  try_mean_bark_thickness_cm,
  mean_bark_thickness_cm,
  bark_thickness_citation,
  bark_diameter_ratio,
  bark_diameter_source
FROM fire_characteristics