CREATE TABLE plot (
        CN bigint,
        SRV_CN bigint,
        CTY_CN bigint,
        PREV_PLT_CN double precision,
        INVYR smallint,
        STATECD smallint,
        UNITCD smallint,
        COUNTYCD smallint,
        PLOT smallint,
        PLOT_STATUS_CD smallint,
        PLOT_NONSAMPLE_REASN_CD double precision,
        MEASYEAR smallint,
        MEASMON smallint,
        MEASDAY smallint,
        REMPER double precision,
        KINDCD smallint,
        DESIGNCD smallint,
        RDDISTCD double precision,
        WATERCD double precision,
        LAT double precision,
        LON text,
        ELEV double precision,
        GROW_TYP_CD smallint,
        MORT_TYP_CD smallint,
        P2PANEL double precision,
        P3PANEL double precision,
        ECOSUBCD text,
        CONGCD smallint,
        MANUAL double precision,
        KINDCD_NC double precision,
        QA_STATUS double precision,
        CREATED_BY text,
        CREATED_DATE text,
        CREATED_IN_INSTANCE bigint,
        MODIFIED_BY text,
        MODIFIED_DATE text,
        MODIFIED_IN_INSTANCE bigint,
        MICROPLOT_LOC double precision,
        DECLINATION double precision,
        EMAP_HEX double precision,
        SAMP_METHOD_CD smallint,
        SUBP_EXAMINE_CD smallint,
        MACRO_BREAKPOINT_DIA double precision,
        INTENSITY double precision,
        CYCLE smallint,
        SUBCYCLE smallint,
        ECO_UNIT_PNW double precision,
        TOPO_POSITION_PNW double precision,
        NF_SAMPLING_STATUS_CD double precision,
        NF_PLOT_STATUS_CD double precision,
        NF_PLOT_NONSAMPLE_REASN_CD double precision,
        P2VEG_SAMPLING_STATUS_CD double precision,
        P2VEG_SAMPLING_LEVEL_DETAIL_CD double precision,
        INVASIVE_SAMPLING_STATUS_CD double precision,
        INVASIVE_SPECIMEN_RULE_CD double precision,
        DESIGNCD_P2A double precision,
        MANUAL_DB double precision,
        SUBPANEL double precision,
        CONDCHNGCD_RMRS double precision,
        FUTFORCD_RMRS double precision,
        MANUAL_NCRS double precision,
        MANUAL_NERS double precision,
        MANUAL_RMRS double precision,
        PAC_ISLAND_PNWRS double precision,
        PLOT_SEASON_NERS double precision,
        PRECIPITATION double precision,
        PREV_MICROPLOT_LOC_RMRS double precision,
        PREV_PLOT_STATUS_CD_RMRS double precision,
        REUSECD1 double precision,
        REUSECD2 double precision,
        REUSECD3 double precision,
        GRND_LYR_SAMPLING_STATUS_CD double precision,
        GRND_LYR_SAMPLING_METHOD_CD double precision
);