CREATE TABLE tree (
        CN bigint,
        PLT_CN bigint,
        PREV_TRE_CN double precision,
        INVYR smallint,
        STATECD smallint,
        UNITCD smallint,
        COUNTYCD smallint,
        PLOT smallint,
        SUBP smallint,
        TREE bigint,
        CONDID smallint,
        AZIMUTH double precision,
        DIST double precision,
        PREVCOND smallint,
        STATUSCD smallint,
        SPCD double precision,
        SPGRPCD smallint,
        DIA double precision,
        DIAHTCD smallint,
        HT double precision,
        HTCD double precision,
        ACTUALHT double precision,
        TREECLCD smallint,
        CR double precision,
        CCLCD double precision,
        TREEGRCD double precision,
        AGENTCD smallint,
        CULL double precision,
        DAMLOC1 double precision,
        DAMTYP1 double precision,
        DAMSEV1 double precision,
        DAMLOC2 double precision,
        DAMTYP2 double precision,
        DAMSEV2 double precision,
        DECAYCD double precision,
        STOCKING double precision,
        WDLDSTEM double precision,
        VOLCFNET double precision,
        VOLCFGRS double precision,
        VOLCSNET double precision,
        VOLCSGRS double precision,
        VOLBFNET double precision,
        VOLBFGRS double precision,
        VOLCFSND double precision,
        DIACHECK double precision,
        MORTYR double precision,
        SALVCD double precision,
        UNCRCD double precision,
        CPOSCD double precision,
        CLIGHTCD double precision,
        CVIGORCD double precision,
        CDENCD double precision,
        CDIEBKCD double precision,
        TRANSCD double precision,
        TREEHISTCD double precision,
        BHAGE double precision,
        TOTAGE double precision,
        CULLDEAD double precision,
        CULLFORM double precision,
        CULLMSTOP double precision,
        CULLBF double precision,
        CULLCF double precision,
        BFSND double precision,
        CFSND double precision,
        SAWHT double precision,
        BOLEHT double precision,
        FORMCL double precision,
        HTCALC double precision,
        HRDWD_CLUMP_CD double precision,
        SITREE double precision,
        CREATED_BY text,
        CREATED_DATE text,
        CREATED_IN_INSTANCE bigint,
        MODIFIED_BY text,
        MODIFIED_DATE text,
        MODIFIED_IN_INSTANCE bigint,
        MORTCD double precision,
        HTDMP double precision,
        ROUGHCULL double precision,
        MIST_CL_CD double precision,
        CULL_FLD double precision,
        RECONCILECD double precision,
        PREVDIA double precision,
        P2A_GRM_FLG text,
        TREECLCD_NERS double precision,
        TREECLCD_SRS double precision,
        TREECLCD_NCRS double precision,
        TREECLCD_RMRS double precision,
        STANDING_DEAD_CD double precision,
        PREV_STATUS_CD double precision,
        PREV_WDLDSTEM double precision,
        TPA_UNADJ double precision,
        DRYBIO_BOLE double precision,
        DRYBIO_STUMP double precision,
        DRYBIO_BG double precision,
        CARBON_AG double precision,
        CARBON_BG double precision,
        CYCLE smallint,
        SUBCYCLE smallint,
        BORED_CD_PNWRS double precision,
        DAMLOC1_PNWRS double precision,
        DAMLOC2_PNWRS double precision,
        DIACHECK_PNWRS double precision,
        DMG_AGENT1_CD_PNWRS double precision,
        DMG_AGENT2_CD_PNWRS double precision,
        DMG_AGENT3_CD_PNWRS double precision,
        MIST_CL_CD_PNWRS double precision,
        SEVERITY1_CD_PNWRS double precision,
        SEVERITY1A_CD_PNWRS double precision,
        SEVERITY1B_CD_PNWRS double precision,
        SEVERITY2_CD_PNWRS double precision,
        SEVERITY2A_CD_PNWRS double precision,
        SEVERITY2B_CD_PNWRS double precision,
        SEVERITY3_CD_PNWRS double precision,
        UNKNOWN_DAMTYP1_PNWRS double precision,
        UNKNOWN_DAMTYP2_PNWRS double precision,
        PREV_PNTN_SRS double precision,
        DISEASE_SRS double precision,
        DIEBACK_SEVERITY_SRS double precision,
        DAMAGE_AGENT_CD1 double precision,
        DAMAGE_AGENT_CD2 double precision,
        DAMAGE_AGENT_CD3 double precision,
        CENTROID_DIA double precision,
        CENTROID_DIA_HT double precision,
        CENTROID_DIA_HT_ACTUAL double precision,
        UPPER_DIA double precision,
        UPPER_DIA_HT double precision,
        VOLCSSND double precision,
        DRYBIO_SAWLOG double precision,
        DAMAGE_AGENT_CD1_SRS double precision,
        DAMAGE_AGENT_CD2_SRS double precision,
        DAMAGE_AGENT_CD3_SRS double precision,
        DRYBIO_AG double precision,
        ACTUALHT_CALC double precision,
        ACTUALHT_CALC_CD double precision,
        CULL_BF_ROTTEN double precision,
        CULL_BF_ROTTEN_CD double precision,
        CULL_BF_ROUGH double precision,
        CULL_BF_ROUGH_CD double precision,
        PREVDIA_FLD double precision,
        TREECLCD_31_NCRS double precision,
        TREE_GRADE_NCRS double precision,
        BOUGHS_AVAILABLE_NCRS double precision,
        BOUGHS_HRVST_NCRS double precision,
        TREECLCD_31_NERS double precision,
        AGENTCD_NERS double precision,
        BFSNDCD_NERS double precision,
        AGECHKCD_RMRS double precision,
        PREV_ACTUALHT_RMRS double precision,
        PREV_AGECHKCD_RMRS double precision,
        PREV_BHAGE_RMRS double precision,
        PREV_HT_RMRS double precision,
        PREV_TOTAGE_RMRS double precision,
        PREV_TREECLCD_RMRS double precision,
        RADAGECD_RMRS double precision,
        RADGRW_RMRS double precision,
        VOLBSGRS double precision,
        VOLBSNET double precision,
        SAPLING_FUSIFORM_SRS double precision,
        EPIPHYTE_PNWRS double precision,
        ROOT_HT_PNWRS double precision,
        CAVITY_USE_PNWRS double precision,
        CORE_LENGTH_PNWRS double precision,
        CULTURALLY_KILLED_PNWRS double precision,
        DIA_EST_PNWRS double precision,
        GST_PNWRS double precision,
        INC10YR_PNWRS double precision,
        INC5YRHT_PNWRS double precision,
        INC5YR_PNWRS double precision,
        RING_COUNT_INNER_2INCHES_PNWRS double precision,
        RING_COUNT_PNWRS double precision,
        SNAG_DIS_CD_PNWRS double precision,
        CONEPRESCD1 double precision,
        CONEPRESCD2 double precision,
        CONEPRESCD3 double precision,
        MASTCD double precision,
        VOLTSGRS double precision,
        VOLTSGRS_BARK double precision,
        VOLTSSND double precision,
        VOLTSSND_BARK double precision,
        VOLCFGRS_STUMP double precision,
        VOLCFGRS_STUMP_BARK double precision,
        VOLCFSND_STUMP double precision,
        VOLCFSND_STUMP_BARK double precision,
        VOLCFGRS_BARK double precision,
        VOLCFGRS_TOP double precision,
        VOLCFGRS_TOP_BARK double precision,
        VOLCFSND_BARK double precision,
        VOLCFSND_TOP double precision,
        VOLCFSND_TOP_BARK double precision,
        VOLCFNET_BARK double precision,
        VOLCSGRS_BARK double precision,
        VOLCSSND_BARK double precision,
        VOLCSNET_BARK double precision,
        DRYBIO_STEM double precision,
        DRYBIO_STEM_BARK double precision,
        DRYBIO_STUMP_BARK double precision,
        DRYBIO_BOLE_BARK double precision,
        DRYBIO_BRANCH double precision,
        DRYBIO_FOLIAGE double precision,
        DRYBIO_SAWLOG_BARK double precision,
        PREV_ACTUALHT_FLD double precision,
        PREV_HT_FLD double precision
);